import { Widget } from '../base/widget.js';

window.showDocsWindow = function(docsObject = window.doc) {
    console.log("got docs object ok");
    
    const jsonContent = JSON.stringify(docsObject, null, 2);
    const dataUrl = 'data:application/json;charset=utf-8,' + encodeURIComponent(jsonContent);
    
    console.log("Opening in new tab...");
    const newTab = window.open(dataUrl, '_blank');
    
    if (!newTab) {
        console.error("❌ Failed to open tab");
    } else {
        console.log("✅ Opened in new tab");
    }
    
    return newTab;
};

// Auto-discovery function that finds all widgets
window.generateWidgetDocs = function() {
    const doc = {};
    
    // Go through all global variables
    for (const key of window.genDocs) {
        console.log(">>", key);
        try {
            const obj = window.gen
            
            // Check if it's a Widget instance (using instanceof)
            if (obj && obj instanceof Widget) {
                console.log(`📋 Found widget: ${key} (${obj.constructor.name})`);
                doc[key] = obj.getAPITree();
            }
        } catch (e) {
            // Skip any problematic objects
            continue;
        }
    }
    
    console.log(`📋 Auto-discovered ${Object.keys(doc).length} widgets:`, Object.keys(doc));
    return doc;
};

// Also add this helper that creates window.doc automatically
window.autoGenerateDocs = function() {
    window.doc = window.generateWidgetDocs();
    console.log("📋 window.doc auto-generated:", window.doc);
    return window.doc;
};
